exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('cars').del()
    .then(function () {
      // Inserts seed entries
      return knex('cars').insert([
        { year: '2018',
          make: 'Honda',
          model: 'Accord',
          trim: 'LX',
          engine: '1.5L 4cyl',
          drive_type: 'FWD',
          body_type: 'Sedan',
          ext_color: 'White',
          int_color: 'Beige',
          transmission: 'AT',
          price: 24000,
          sale: 10,
          vin: '1H5BV1F15AA033979',
        },
        { year: '2018',
          make: 'Honda',
          model: 'Civic',
          trim: 'LX',
          engine: '1.5L 4cyl',
          drive_type: 'FWD',
          body_type: 'Hatchback',
          ext_color: 'Polished Metal',
          int_color: 'Black/Ivory',
          transmission: 'AT',
          price: 21000,
          sale: 10,
          vin: '1H5BV1F15AA034979',
        },
        { year: '2018',
          make: 'Honda',
          model: 'Odyssey',
          trim: 'LX',
          engine: '3.5L V-6cyl',
          drive_type: 'FWD',
          body_type: 'Van',
          ext_color: 'White',
          int_color: 'Beige',
          transmission: '9 Speed AT',
          price: 30930,
          sale: 0
          vin: '1H5NV1F15AA034979',
        },
        { year: '2018',
          make: 'Honda',
          model: 'CR-V',
          trim: 'LX',
          engine: '2.4L 4cyl',
          drive_type: 'FWD',
          body_type: 'SUV',
          ext_color: 'Gray',
          int_color: 'Black',
          transmission: 'AT',
          price: 25000,
          sale: 0
          vin: '1H5NV4F15AA034976',
        },
        { year: '2018',
          make: 'Honda',
          model: 'HR-V',
          trim: 'LX',
          engine: '1.8L 4cyl',
          drive_type: 'FWD',
          body_type: 'SUV',
          ext_color: 'White',
          int_color: 'Gray',
          transmission: 'AT',
          price: 21000,
          sale: 0
          vin: '1H5FV4F15CA034976',
        },
        { year: '2018',
          make: 'Toyota',
          model: '4Runner',
          trim: 'SR5',
          engine: '4.0L V-6cyl',
          drive_type: 'FWD',
          body_type: 'SUV',
          ext_color: 'White',
          int_color: 'Gray',
          transmission: 'AT',
          price: 33000,
          sale: 0
          vin: '1H5FV4F15CA024946',
        },
        { year: '2018',
          make: 'Toyota',
          model: 'Avalon',
          trim: 'XLE',
          engine: '3.5L V-6cyl',
          drive_type: 'FWD',
          body_type: 'Sedan',
          ext_color: 'White',
          int_color: 'Light Gray',
          transmission: 'AT',
          price: 29000,
          sale: 0
          vin: '1H5FB4F15CA024846',
        },
        { year: '2018',
          make: 'Toyota',
          model: 'Camry',
          trim: 'LE',
          engine: '2.5L 4cyl',
          drive_type: 'FWD',
          body_type: 'Sedan',
          ext_color: 'Black',
          int_color: 'Midnight Black',
          transmission: 'AT',
          price: 23000,
          sale: 0
          vin: '1F5FB4F12CA024841',
        },
        { year: '2018',
          make: 'Toyota',
          model: 'Tocoma',
          trim: 'SR',
          engine: '2.7L 4cyl',
          drive_type: 'FWD',
          body_type: 'Truck',
          ext_color: 'White',
          int_color: 'Gray',
          transmission: 'AT',
          price: 23593,
          sale: 0
          vin: '3F5FB4F12DA024811',
        },
        { year: '2018',
          make: 'Toyota',
          model: 'Tundra',
          trim: 'SR',
          engine: '4.6L V-8cyl',
          drive_type: 'FWD',
          body_type: 'Truck',
          ext_color: 'White',
          int_color: 'Gray',
          transmission: 'AT',
          price: 30593,
          sale: 0
          vin: '3F5FE4F12DA0T4811',
        },
        { year: '2018',
          make: 'Mercedes-benz',
          model: 'C-Class',
          trim: 'C300',
          engine: '2.0L 4cyl',
          drive_type: 'AWD',
          body_type: 'Sedan',
          ext_color: 'White',
          int_color: 'Black',
          transmission: 'AT',
          price: 42865,
          sale: 0
          vin: '3F5FE4F11DA0T4111',
        },
        { year: '2018',
          make: 'Mercedes-benz',
          model: 'C-Class',
          trim: 'AMG-C43',
          engine: '4.0L 8cyl',
          drive_type: 'AWD',
          body_type: 'Convertible',
          ext_color: 'White',
          int_color: 'Brown',
          transmission: 'AT',
          price: 42865,
          sale: 0
          vin: '3M5FE4F11DH0T4111',
        },
        { year: '2018',
          make: 'Mercedes-benz',
          model: 'C-Class',
          trim: 'C-300',
          engine: '4.0L 8cyl',
          drive_type: 'AWD',
          body_type: 'Coupe',
          ext_color: 'White',
          int_color: 'Black',
          transmission: 'AT',
          price: 51000,
          sale: 0
          vin: '9F5FE4F11DA0T4111',
        },

      ]);
    });
};
