exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('cars').del()
    .then(function () {
      // Inserts seed entries
      return knex('cars').insert([
        { year: '2018',
          make: 'Honda',
          model: 'Accord',
          trim: 'LX',
          engine: '1.5L 4cyl',
          drive_type: 'FWD',
          body_type: 'Sedan',
          ext_color: 'White',
          int_color: 'Beige',
          transmission: 'AT',
          price: 24000,
          sale: 10,
          vin: '1H5BV1F15AA033979',
        },
        { year: '2018',
          make: 'Honda',
          model: 'Civic',
          trim: 'LX',
          engine: '1.5L 4cyl',
          drive_type: 'FWD',
          body_type: 'Hatchback',
          ext_color: 'Polished Metal',
          int_color: 'Black/Ivory',
          transmission: 'AT',
          price: 21000,
          sale: 10,
          vin: '1H5BV1F15AA034979',
        },
        { year: '2018',
          make: 'Honda',
          model: 'Odyssey',
          trim: 'LX',
          engine: '3.5L V-6cyl',
          drive_type: 'FWD',
          body_type: 'Van',
          ext_color: 'White',
          int_color: 'Beige',
          transmission: '9 Speed AT',
          price: 30930,
          sale: 0
          vin: '1H5NV1F15AA034979',
        },
        { year: '2018',
          make: 'Honda',
          model: 'CR-V',
          trim: 'LX',
          engine: '2.4L 4cyl',
          drive_type: 'FWD',
          body_type: 'SUV',
          ext_color: 'Gray',
          int_color: 'Black',
          transmission: 'AT',
          price: 25000,
          sale: 0
          vin: '1H5NV4F15AA034976',
        },
        { year: '2018',
          make: 'Honda',
          model: 'HR-V',
          trim: 'LX',
          engine: '1.8L 4cyl',
          drive_type: 'FWD',
          body_type: 'SUV',
          ext_color: 'White',
          int_color: 'Gray',
          transmission: 'AT',
          price: 25000,
          sale: 0
          vin: '1H5NV4F15AA034976',
        },

      ]);
    });
};
